### PR TITLE
Add support for JSON serialization

### LINKED ISSUE #456: Support creating manifests as JSON
Trenly I think you are on to something. I went through `wingetcreate` again and added the `AppsAndFeaturesEntries`. `wingetcreate` gives me a YAML file, but my repository only accepts JSON files. Unfortunately, I am stupid and do not know how I would go about converting this to the format that would be accepted by the JSON. Any assistance you could provide would be much appreciated. Below is the relevant part of the YAML file that I would need to be in JSON.

```
AppsAndFeaturesEntries:
- DisplayName: SAP GUI for Windows 8.00 32bit  (Patch 3)
  Publisher: SAP SE
  DisplayVersion: 8.00 Compilation 1
- DisplayName: SAP Business Client 8.00
  Publisher: SAP SE
  DisplayVersion: 8.00 PL0
- DisplayName: SAP PDFPRINT for SAP GUI 8.00
  Publisher: SAP SE
- DisplayName: SAP Business Explorer
  Publisher: SAP SE
  DisplayVersion: "8.00"
- DisplayName: 64Bit RFC Controls
  Publisher: SAP SE
  DisplayVersion: "8.00"
```

_Originally posted by @Smith8154 in https://github.com/microsoft/winget-cli/issues/3674#issuecomment-1739577749_

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Are you working against an Issue?
	- Resolves #456

### Changes
- Add a new CLI arg `--format` to specify output manifest format (json, yaml etc).
- Added a new user setting to specify the manifest format (inline `--format` arg takes precedence over this value)
- Refactored current Serialization.cs for future extension of other serializations
- Added check to only allow YAML submissions to community repository
- Implemented support for deserialization from local files / GitHub repo contents of JSON format. Refactored GitHub flow to allow submission of json manifests.

### Validations

Added E2E tests for JSON, and added a bunch of unit tests.

> [!IMPORTANT]
> The tests will only pass once changes in https://github.com/microsoft/winget-pkgs-submission-test/pull/4784 are merged since I had to refactor the directory structures as well. For local testing, you can pull the changes in that PR to the master branch of your fork and run the tests locally;

cc @denelon @Trenly from the original issue for any naming/design considerations

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-create/pull/507)

### CODE REVIEW

**Comment by denelon** [comment]
wingetcreate doesnt' necessarily need to serialize as JSON. YAML serialization is fine as long as wingetcreate knows how to transform the YAML file-based manifests to the JSON expected by a WinGet source REST endpoint.

The same would be true in terms of the upgrade scenario where the package ID and source are REST based. The transformation from JSON to YAML could happen inside wingetcreate.

**Comment by denelon** [comment]
I'm not opposed to this, but we should be careful in terms of how we decide which format wingetcreate defaults to and how we do any of the transformations.

**Comment by denelon** [comment]
No worries :)

If @ryfu-msft is good with it, then I am too.

**Comment by ryfu-msft** [comment]
@mdanish-kh, will take a look at this soon. 

I want to create a new release for winget-create to support 1.6 manifests first since there are a lot of your new features in there. This will be included in our next 1.7 release.

**Comment by ryfu-msft** [comment]
I have merged https://github.com/microsoft/winget-pkgs-submission-test/pull/4784 so that these tests will pass. We will need to get this in first so that #512 can pull in latest changes.

**Review by ryfu-msft — APPROVED** [review]
Really awesome feature :)

**Pull request merged**
