### PR TITLE
Match compatible installers

### LINKED ISSUE #214: Multiple matches found for X64 installer
### Brief description of your issue

Running `wingetcreate update` presents the following error

`.\wingetcreate.exe update isaaclevin.presencelight -u https://github.com/isaacrlevin/presencelight/releases/download/Desktop-v4.4.9/PresenceLight.Package_4.4.9.0_x64.appxbundle`

```
Each new installer URL must have a single match to an existing installer based on installer type and architecture. The following installers failed to match an existing installer:
Multiple matches found for X64 Msix installer detected from the url: https://github.com/isaacrlevin/presencelight/releases/download/Desktop-v4.4.9/PresenceLight.Package_4.4.9.0_x64.appxbundle
```

Experience similar to #198

### Steps to reproduce

1. Download WinGet Creator
2. Run against any version of PresenceLight

`.\wingetcreate.exe update isaaclevin.presencelight -u https://github.com/isaacrlevin/presencelight/releases/download/Desktop-v4.4.9/PresenceLight.Package_4.4.9.0_x64.appxbundle`

### Expected behavior

Manifest file gets created

### Actual behavior

Get following errors message

image

### Environment

```shell
Windows Package Manager (Preview) v1.2.3411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22533.1001
Package: Microsoft.DesktopAppInstaller v1.17.3411.0
```
```

### PR DESCRIPTION
**Pull request by ryfu-msft**
Fixes #214 

Issue:
Winget-Create's update command matches based on the exact installerType. This can cause matching failures even when trying to match compatible installerTypes
such as appx -> msix.

Changes:
I have improved the matching logic so that if the update command fails to find a match using the exact installerType, the tool will resort to looking for a compatible installerType. 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-create/pull/217)

### CODE REVIEW

**Comment by palenshus** [comment]
I thought long ago we'd decided to coalesce all appx and msix packages to "msix" in winget-create, wasn't that right @denelon ?

**Comment by ryfu-msft** [comment]
> I thought long ago we'd decided to coalesce all appx and msix packages to "msix" in winget-create, wasn't that right @denelon ?

Now that you bring it up, I think I do remember us having that discussion and we wanted to make "msix" the default. As @yao-msft pointed out, a better solution would be to improve our matching logic so that msix can be assigned to an appx, rather than have the two installerTypes be completely separate.

**Comment by denelon** [comment]
Yes, they should "all" be treated as "MSIX" installers.

**Review by yao-msft — APPROVED** [review]
:shipit:

**Pull request merged**
