### PR TITLE
SameFilename2

### LINKED ISSUE #249: Incorrect hashes computed when installer file names are not unique
### Brief description of your issue

When multiple installer URLs are passed that use a common name, winget-create overwrites the downloaded file in the temp directory and subsequently computes the same hash for the different variants.

### Steps to reproduce

Run
```
wingetcreate update WillowSoftware.AnvilStudio -v 22.03.02 -u https://anvilstudio.com/x/asinstall.exe https://anvilstudio.com/x64/asinstall.exe
```

### Expected behavior

The generated manifest should contain the correct file hashes for the two installer variants.

### Actual behavior

The generated manifest contains the wrong file hash for the x86 variant:
```yaml
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://anvilstudio.com/x64/asinstall.exe
  InstallerSha256: 02FC70CD7CCC165A1F9089F0EF29BD3BA2E1A0374D502A7E7784E7BA5C21AE46
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://anvilstudio.com/x/asinstall.exe
  InstallerSha256: 02FC70CD7CCC165A1F9089F0EF29BD3BA2E1A0374D502A7E7784E7BA5C21AE46
```

### Environment

```shell
Windows Manifest Creator v1.0.3.0
```

### PR DESCRIPTION
**Pull request by Trenly**
- Increment filename when similar files already existing
- Simplify to be count of files
- Move numeric filename to function
- Reset Stream Position when Seekable

* Resolves #249
* Resolves #263 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-create/pull/262)

### CODE REVIEW

**Comment by Trenly** [comment]
😭

**Comment by ryfu-msft** [comment]
Let me try creating a PR and seeing if I encounter the same issue, I haven't encountered this issue before so I'll need to do some digging.

**Comment by ryfu-msft** [comment]
#263  same problem :( 

Service might be down, let's try again tomorrow, I'll keep monitoring it to see if it starts working again.

**Comment by Trenly** [comment]
> #263 same problem :(
> 
> Service might be down, let's try again tomorrow, I'll keep monitoring it to see if it starts working again.

Thank you

**Comment by ryfu-msft** [comment]
@Trenly, it works now!

**Comment by Trenly** [comment]
Yay! Now just to fix the other test 👍

**Review by ryfu-msft — APPROVED** [review]
:shipit:

**Comment by ryfu-msft** [comment]
Thank you for the huge help :)

**Comment by Trenly** [comment]
> Thank you for the huge help :)

No, thank you for your help figuring out the unit test issue

**Pull request merged**
